spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              create-source: metadata
              drop-source: metadata
              create-target: src/main/resources/sql/create-table.sql
              drop-target: src/main/resources/sql/drop-table.sql
